# Site settings
title: OldUfa. Фотографии старой Уфы.
email: your-email@domain.com
description: OldUfa
baseurl: ""
url: "http://oldufa.org"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
